#!/bin/bash

mkdir -p ~/lib  && cd ~/lib

#
# quarto
#
git clone https://github.com/quarto-dev/quarto-cli
cd quarto-cli
./configure.sh

# tex 4 quarto
quarto install tinytex --update-path

# go to home
cd ~/
