#!/bin/bash

# create lib folder
mkdir -p ~/lib && cd ~/lib

#
# saxon-lint
#
git clone https://github.com/sputnick-dev/saxon-lint.git
cd saxon-lint*
chmod +x saxon-lint.pl

# add saxon-lint.pl to PATH variable
echo "PATH=$PATH:~/lib/saxon-lint" >> ~/.bashrc

# make an alias
echo "alias saxon-lint='saxon-lint.pl'" >> ~/.bashrc

#
# Tikal
#
cd ~/lib
wget https://okapiframework.org/binaries/main/1.47.0/okapi-apps_gtk2-linux-x86_64_1.47.0.zip
unzip okapi-apps_gtk2-linux-x86_64_1.47.0.zip -d ./okapi
rm okapi-apps_gtk2-linux-x86_64_1.47.0.zip
cd ./okapi
chmod +x tikal.sh

# add okapi to PATH variable
echo "PATH=$PATH:~/lib/okapi" >> ~/.bashrc

# make an alias
echo "alias tikal='tikal.sh'" >> ~/.bashrc

# validation
source ~/.bashrc

# go to home
cd ~/
