#!/bin/bash

# create lib folder
mkdir -p ~/lib && cd ~/lib

#
# quarto
#
#wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.56/quarto-1.5.56-linux-amd64.deb
wget https://quarto.org/download/latest/quarto-linux-amd64.deb

dpkg -i quarto-linux-amd64.deb
