---
title: "TMX : construire des mémoires de traduction"
title-slide-attributes:
  data-background-color: "#002f2f"
author: "Alexandre Roulois (Université Paris-Cité, IRIF, CNRS)"
format:
  pdf:
    toc: true
  revealjs:
    slide-number: true
    show-slide-number: all
    smaller: true
    scrollable: true
    theme: showcase.scss
---

## Présentation

**TMX :** *Translation Memory eXchange*

Format de fichier basé sur XML pour la traduction en plusieurs langues :

- développé par LISA (*Localization Industry Standards Association**), insolvable en 2011
- repris en 2014 par [GALA](https://www.gala-global.org/knowledge-center/industry-development/standards/lisa-oscar-standards){target="_blank"} (*Globalization & Localization Association*)
- largement utilisé pour constituer des corpus parallèles
- technologie de l’architecture ouverte pour la création et la localisation (OAXAL)

:::: {.columns}

::: {.column}
**Avantages :**

- Vocabulaire réduit
- Données humainement lisibles
- Détection aisée de traductions manquantes
:::

::: {.column}
**Corpus parallèles au format TMX :**

- Europarl
- OpenSubtitles
- Wikipedia
- …
:::

::::

## Aspects techniques

**Version 1.4b :** [Documentation](https://www.gala-global.org/tmx-14b){target="_blank"}

**DTD :** [Feuille des déclarations](https://www.gala-global.org/sites/default/files/migrated-pages/docs/tmx14%20%281%29.dtd){target="_blank"}

**Encodage :**

- Format Unicode seul : UTF-8, UTF-16 ou ISO-646 (US-ASCII)
- 5 références d’entités `&amp;` `&lt;` `&gt;` `&apos;` `&quot;`
- Représentation numérique pour les caractères non-ASCII : `#230` `#167` …

---

### Éléments

:::: {.columns}

::: {.column}
**Racine :** `<tmx>`

**Éléments structurels :**

`<body>` `<header>` `<map/>` `<note>` `<prop>` `<seg>` `<tmx>` `<tu>` `<tuv>` `<ude>`

**Éléments en ligne :**

`<bpt>` `<ept>` `<hi>` `<it>` `<ph>` `<sub>` `<ut>`
:::

::: {.column}
```xml
<tmx version="1.4">
  <header
    creationtool=""
    creationtoolversion=""
    segtype=""
    o-tmf=""
    adminlang=""
    srclang=""
    datatype="">
  </header>
  <body>
    <!-- Place here the content -->
  </body>
</tmx>
```
:::

::::

---

### Attributs notables

| Attribut | Description | Valeur
|:-:|-|:-:|
|`creationdate`|Date de création de l’élément|Format ISO 8601 : `YYYYMMDDThhmmssZ`|
|`creationid`|Identifiant de l’auteur responsable de la création de l’élément|Chaîne de caractères|
|`changedate`|Date de la dernière modification de l’élément|Format ISO 8601 : `YYYYMMDDThhmmssZ`|
|`changeid`|Identifiant de l’auteur responsable de la dernière modification de l’élément|Chaîne de caractères|
|`tuid`|Identifiant pour un élément `tu`|Chaîne de caractères|
|`o-encoding`|Encodage de l’original|Chaîne de caractères|

: {tbl-colwidths="[25,50,25]"}

## Mécanique

Élément `<tu>` au centre de TMX : *Translation Unit*

Reçoit le terme et ses différentes traductions au sein d'éléments `<tuv>` : *Translation Unit Variant*

Une variante est éventuellement composée de notes `<note>`, de propriétés `<prop>`, et obligatoirement du segment traduit `<seg>`

```xml
<tu>
  <tuv xml:lang="en">
    <seg>Hello World!</seg>
  </tuv>
  <tuv xml:lang="fr">
    <seg>Bonjour monde !</seg>
    <note>To improve! Does not seem accurate.</note>
  </tuv>
</tu>
```

---

Haïku de Matsuo Bashō en quatre langues :

:::: {.columns}

::: {.column}
**Japonais**

>古池や  
蛙飛込む  
水の音
:::

::: {.column}
**Japonais** (transcription alphabétique)

>furuike ya  
kawazu tobikomu  
mizu no oto
:::

::::

:::: {.columns}

::: {.column}
**Français**

>Un vieil étang et  
Une grenouille qui plonge  
Le bruit de l'eau
:::

::: {.column}
**Anglais**

>Old pond  
A frog leaps in  
Water's sound
:::

::::

---

:::: {.columns}

::: {.column}
**Structure du fichier TMX**

```xml
<tmx version="1.4">
  <header
    creationtool="Sublime Text"
    creationtoolversion="3"
    segtype="phrase"
    o-tmf="undefined"
    adminlang="fr"
    srclang="ja"
    datatype="plaintext">
  </header>
  <body>
    <!-- Translation units should be placed here -->
  </body>
</tmx>
```
:::

::: {.column}
**Premier vers**

```xml
<body>
  <tu>
    <tuv xml:lang="ja">
      <seg>古池や</seg>
    </tuv>
    <tuv xml:lang="ja-Latn">
      <seg>furuike ya</seg>
    </tuv>
    <tuv xml:lang="fr">
      <seg>Un vieil étang et</seg>
    </tuv>
    <tuv xml:lang="en">
      <seg>Old pond</seg>
    </tuv>
  </tu>
  <!-- Second and third lines are exepected below -->
</body>
```
:::

::::

---

:::: {.columns}

::: {.column}
**Second vers**

```xml
<body>
  <!-- First line -->
  …
  <!-- Second line -->
  <tu>
    <tuv xml:lang="ja">
      <seg>蛙飛込む</seg>
    </tuv>
    <tuv xml:lang="ja-Latn">
      <seg>kawazu tobikomu</seg>
    </tuv>
    <tuv xml:lang="fr">
      <seg>Une grenouille qui plonge</seg>
    </tuv>
    <tuv xml:lang="en">
      <seg>A frog leaps in</seg>
    </tuv>
  </tu>
  <!-- Third line -->
  …
  <!-- Second and third lines are exepected below -->
</body>
```
:::

::: {.column}
**Troisième vers**
```xml
<body>
  <!-- First line -->
  …
  <!-- Second line -->
  …
  <!-- Third line -->
  <tu>
    <tuv xml:lang="ja">
      <seg>水の音</seg>
    </tuv>
    <tuv xml:lang="ja-Latn">
      <seg>mizu no oto</seg>
    </tuv>
    <tuv xml:lang="fr">
      <seg>Le bruit de l’eau</seg>
    </tuv>
    <tuv xml:lang="en">
      <seg>Water's sound</seg>
    </tuv>
  </tu>
</body>
```
:::

::::

## Présentation de corpus

### Europarl v7

Corpus parallèle à destination des robots (TAL, statistiques…)

Sessions du parlement européen 1996-2011 (11 langues, 600M+  de mots)

**TXT :** [http://www.statmt.org/europarl/index.html](http://www.statmt.org/europarl/index.html){target="_blank"}

**TMX :** [http://opus.lingfil.uu.se/Europarl.php](http://opus.lingfil.uu.se/Europarl.php){target="_blank"}

:::: {.columns}

::: {.column}
**Fichier FR**
```txt
Reprise de la session
Je déclare reprise la session du Parlement européen qui avait été interrompue le vendredi 17 décembre dernier et je vous renouvelle tous mes vux en espérant que vous avez passé de bonnes vacances.
Comme vous avez pu le constater, le grand "bogue de l'an 2000" ne s'est pas produit. En revanche, les citoyens d'un certain nombre de nos pays ont été victimes de catastrophes naturelles qui ont vraiment été terribles.
Vous avez souhaité un débat à ce sujet dans les prochains jours, au cours de cette période de session.
En attendant, je souhaiterais, comme un certain nombre de collègues me l'ont demandé, que nous observions une minute de silence pour toutes les victimes, des tempêtes notamment, dans les différents pays de l'Union européenne qui ont été touchés.
Je vous invite à vous lever pour cette minute de silence.
(Le Parlement, debout, observe une minute de silence)
```
:::

::: {.column}
**Fichier EN**
```txt
Resumption of the session
I declare resumed the session of the European Parliament adjourned on Friday 17 December 1999, and I would like once again to wish you a happy new year in the hope that you enjoyed a pleasant festive period.
Although, as you will have seen, the dreaded 'millennium bug' failed to materialise, still the people in a number of countries suffered a series of natural disasters that truly were dreadful.
You have requested a debate on this subject in the course of the next few days, during this part-session.
In the meantime, I should like to observe a minute' s silence, as a number of Members have requested, on behalf of all the victims concerned, particularly those of the terrible storms, in the various countries of the European Union.
Please rise, then, for this minute' s silence.
(The House rose and observed a minute' s silence)
```
:::

::::

---

**Version TMX**

```xml
<tmx version="1.4">
  <header adminlang="en" creationdate="Mon Jan 16 10:29:40 2017" creationtool="Uplug" creationtoolversion="unknown" datatype="PlainText" o-tmf="unknown" segtype="sentence" srclang="en"/>
  <body>
    <tu>
      <tuv xml:lang="fr">
        <seg>Reprise de la session </seg>
      </tuv>
      <tuv xml:lang="en">
        <seg>Resumption of the session </seg>
      </tuv>
    </tu>
    <tu>
      <tuv xml:lang="fr">
        <seg>Je d&#233;clare reprise la session du Parlement europ&#233;en qui avait &#233;t&#233; interrompue le vendredi 17 d&#233;cembre dernier et je vous renouvelle tous mes vux en esp&#233;rant que vous avez pass&#233; de bonnes vacances.</seg>
      </tuv>
      <tuv xml:lang="en">
        <seg>I declare resumed the session of the European Parliament adjourned on Friday 17 December 1999, and I would like once again to wish you a happy new year in the hope that you enjoyed a pleasant festive period.</seg>
      </tuv>
    </tu>
    …
  </body>
</tmx>
```

---

### DGT-TM

Mémoires de traduction dans les 22 langues officielles de la Commission Européenne : [http://data.europa.eu/euodp/en/data/dataset/dgt-translation-memory](http://data.europa.eu/euodp/en/data/dataset/dgt-translation-memory){target="_blank"}

```xml
<tu>
  <prop type="Txt::Doc. No.">52014BP1121(01)</prop>
  <tuv lang="EN-GB">
    <seg>Resolution of the European Parliament</seg>
  </tuv>
  <tuv lang="DE-DE">
    <seg>Entschließung des Europäischen Parlaments</seg>
  </tuv>
  <tuv lang="DA-01">
    <seg>Europa-Parlamentets beslutning</seg>
  </tuv>
  <tuv lang="EL-01">
    <seg>Ψήφισμα του Ευρωπαϊκού Κοινοβουλίου</seg>
  </tuv>
  <tuv lang="ES-ES">
    <seg>Resolución del Parlamento Europeo</seg>
  </tuv>
  …
</tu>
```

---

### Tanaka Corpus

Corpus aligné de 150 000 entrées japonais-anglais : [http://edrdg.org/wiki/index.php/Tanaka_Corpus](http://edrdg.org/wiki/index.php/Tanaka_Corpus){target="_blank"}

```xml
<tu tuid="1" srclang="JA">
  <tuv xml:lang="JA">
    <seg>すぐに戻ります。</seg>
  </tuv>
  <tuv xml:lang="EN">
    <seg>I'll be back in a second.</seg>
  </tuv>
</tu>
<tu tuid="3" srclang="JA">
  <tuv xml:lang="JA">
    <seg>すぐに戻ります。</seg>
  </tuv>
  <tuv xml:lang="EN">
    <seg>I will be back soon.</seg>
  </tuv>
</tu>
<tu tuid="5" srclang="JA">
  <tuv xml:lang="JA">
    <seg>すぐに諦めて昼寝をするかも知れない。</seg>
  </tuv>
  <tuv xml:lang="EN">
    <seg>I may give up soon and just nap instead.</seg>
  </tuv>
</tu>
```

