---
title: "TBX : échanger des unités terminologiques"
title-slide-attributes:
  data-background-color: "#002f2f"
author: "Alexandre Roulois (Université Paris-Cité, IRIF, CNRS)"
format:
  pdf:
    toc: true
  revealjs:
    slide-number: true
    show-slide-number: all
    smaller: true
    scrollable: true
    theme: showcase.scss
---

## Présentation

**TBX :** *TermBase eXchange*

Format de fichier basé sur XML pour représenter et échanger des unités terminologiques :

- développé de 2002 à 2008 par LISA (*Localization Industry Standards Association*), insolvable en 2011
- repris par [GALA](https://www.gala-global.org/resources/industry-standards){target="_blank"} (*Globalization &amp; Localization Association*)
- technologie de l’architecture ouverte pour la création et la localisation (OAXAL)
- norme ISO
- constituer des glossaires

## Aspects techniques

**Version 2008 :** [Documentation](https://www.gala-global.org/sites/default/files/migrated-pages/docs/tbx_oscar_0.pdf){target="_blank"}

**DTD :** [Feuille des déclarations](https://www.gala-global.org/sites/default/files/migrated-pages/docs/TBXcoreStructV02%20%281%29.dtd){target="_blank"}

Nouvelle version en préparation, modulaire :

- TBX-Core
- TBX-Min (glossaire bilingue)
- TBX-Basic (glossaires multingues)

Deux styles de design :

- DCA (*Data Category as Attribute*)
- DCT (*Data Category as Tag*)

---

:::: {.columns}

::: {.column}
**TBX-Core :**

- [Relax NG](https://raw.githubusercontent.com/LTAC-Global/TBX-Basic_dialect/master/DCA/TBXcoreStructV03_TBX-Basic_integrated.rng)
- [Schematron](https://raw.githubusercontent.com/LTAC-Global/TBX-Basic_dialect/master/DCA/TBX-Basic_DCA.sch)

**TBX-Min DCA :**

- [Relax NG](https://raw.githubusercontent.com/LTAC-Global/TBX-Min_dialect/master/DCA/TBXcoreStructV03_TBX-Min_integrated.rng)
- [Schematron](https://raw.githubusercontent.com/LTAC-Global/TBX-Min_dialect/master/DCA/TBX-Min_DCA.sch)

**TBX-Basic DCA :**

- [Relax NG](https://raw.githubusercontent.com/LTAC-Global/TBX-Basic_dialect/master/DCA/TBXcoreStructV03_TBX-Basic_integrated.rng)
- [Schematron](https://raw.githubusercontent.com/LTAC-Global/TBX-Basic_dialect/master/DCA/TBX-Basic_DCA.sch)
:::

::: {.column}
Dialecte TBX-Basic (v3.1) maintenu par [Terminorgs](http://www.terminorgs.net/TBX-Basic.html)

Récupérer tous les schémas :  
<http://www.tbxinfo.net/tbx-dialects/>

Version en cours de standardisation

Conflits entre :

- contraintes des schémas
- documentation
:::

::::

Intégrer les schémas de validation (un seul obligatoire) :

```xml
<!-- Relax NG for TBX Core -->
<?xml-model href="https://raw.githubusercontent.com/LTAC-Global/TBX-Min_dialect/master/DCA/TBXcoreStructV03_TBX-Min_integrated.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<!-- Schematron for TBX Core -->
<?xml-model href="https://raw.githubusercontent.com/LTAC-Global/TBX-Min_dialect/master/DCA/TBX-Min_DCA.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
```

---

:::: {.columns}

::: {.column}
Racine `tbx` attributs :

- `dialect` : nom du module
- `style` : DCA ou DCT
- `xml:lang` : langue principale du document
- `xmlns` : espace de nommage

En-tête `tbxHeader` compatible TEI

Corps :

- élément `text` compatible TEI
- 3 niveaux :
  - concept
  - langue
  - terme
:::

::: {.column}

Structure fichier TBX-Min DCA :

```xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-model href="TBXcoreStructV03_TBX-Min_integrated.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<tbx type="TBX-Min" style="dca" xml:lang="" xmlns="urn:iso:std:iso:30042:ed-2">
  <!-- En-tête -->
  <tbxHeader>
    <fileDesc>
      <sourceDesc>
        <p></p>
      </sourceDesc>
    </fileDesc>
  </tbxHeader>
  <!-- Corps -->
  <text>
    <body>
      <!-- Concept -->
      <conceptEntry id="">
        <!-- Langue -->
        <langSec xml:lang="">
          <!-- Terme -->
          <termSec>
            <term></term>
          </termSec>
        </langSec>
      </conceptEntry>
    </body>
  </text>
</tbx>
```
:::

::::

## Mécanique

Élément `<conceptEntry>` au cœur de TBX :

- concept exprimé en plusieurs langues
- catégorie ou domaine éventuels
- chaque langue plusieurs termes
- chaque terme plusieurs commentaires

Exemple minimal :

```xml
<conceptEntry id="c1">
  <langSec xml:lang="fr">
    <termSec>
      <term>disque d’accrétion</term>
    </termSec>
  </langSec>
</conceptEntry>
```
---

Exemple minimal identifié, avec un sujet et des notes :

```xml
<conceptEntry id="c1">
  <descrip type="subjectField">Naissance d’une étoile</descrip>
  <langSec xml:lang="fr">
    <termSec>
      <term>disque d’accrétion</term>
      <termNote type="partOfSpeech">noun</termNote>
    </termSec>
  </langSec>
</conceptEntry>
```

Exemple avec deux termes synonymes :

```xml
<conceptEntry id="c1">
  <descrip type="subjectField">Naissance d’une étoile</descrip>
  <langSec xml:lang="fr">
    <termSec>
      <term>disque d’accrétion circumstellaire</term>
      <termNote type="partOfSpeech">noun</termNote>
      <termNote type="administrativeStatus">preferredTerm-admn-sts</termNote>
    </termSec>
    <termSec>
      <term>disque d’accrétion</term>
      <termNote type="partOfSpeech">noun</termNote>
      <termNote type="administrativeStatus">admittedTerm-admn-sts</termNote>
    </termSec>
  </langSec>
</conceptEntry>
```

---

Exemple plus complet :

```xml
<conceptEntry id="c1">
  <descrip type="subjectField">Naissance d’une étoile</descrip>
  <langSec xml:lang="fr">
    <termSec>
      <term>disque d’accrétion circumstellaire</term>
      <termNote type="partOfSpeech">noun</termNote>
      <termNote type="administrativeStatus">preferredTerm-admn-sts</termNote>
    </termSec>
    <termSec>
      <term>disque d’accrétion</term>
      <termNote type="partOfSpeech">noun</termNote>
      <termNote type="administrativeStatus">admittedTerm-admn-sts</termNote>
    </termSec>
  </langSec>
  <langSec xml:lang="en">
    <termSec>
      <term>circumstellar accretion disk</term>
      <termNote type="partOfSpeech">noun</termNote>
      <termNote type="administrativeStatus">preferredTerm-admn-sts</termNote>
    </termSec>
    <termSec>
      <term>accretion disk</term>
      <termNote type="partOfSpeech">noun</termNote>
      <termNote type="administrativeStatus">admittedTerm-admn-sts</termNote>
    </termSec>
  </langSec>
</conceptEntry>
```

## Niveau du concept

Élément `conceptEntry` avec attribut obligatoire `id`

- `descrip` : renseigner domaine
- `admin` : documenter source associée à l’entrée
- `langSec` (obligatoire) : langue
- `note` : commentaires

```xml
<conceptEntry id="c1">
  <descrip type="subjectField">Naissance d’une étoile</descrip>
  <admin type="customerSubset"></admin>
  <langSec xml:lang="fr">…</langSec>
  <note>…</note>
</conceptEntry>
```

## Niveau de la langue

Élément `langSec` avec attribut obligatoire `xml:lang`

- `termSec` (obligatoire) : informations sur un terme
- `note` : commentaires

```xml
<langSec xml:lang="fr">
  <termSec></termSec>
  <note>…</note>
</langSec>
```

## Niveau du terme

Élément `termSec` avec attribut optionnel `id`

- `term` (obligatoire)
- `termNote` : partie du discours, statut administratif
- `note` : commentaires

```xml
<termSec id="t12">
  <term>Disque d’accrétion</term>
  <termNote type="partOfSpeech">noun</termNote>
  <termNote type="administrativeStatus">admittedTerm-admn-sts</termNote>
</termSec>
```

## Documentation

|Élément|Description|Attributs
|:-:|-|:-:|
|`admin`|Pour documenter la source associée à l’entrée ou identifier les clients spécifiques. Attribut `type` avec valeur `customerSubset`.|`type`|
|`conceptEntry`|Décrire un concept.|`id`
|`descrip`|Domaine auquel appartient le terme. Attribut `type` avec valeur `subjectField`.|`type`|
|`langSec`|Identifier la langue du terme grâce à l’attribut `xml:lang` qui accepte une valeur compatible RFC 4646.|`xml:lang`|
|`note`|Commentaires.||
|`term`|Terme du lexique.||
|`termNote`|Notes à propos du terme. Attribut `type` avec deux valeurs : `partOfSpeech` ou `administrativeStatus`. La première contraint le contenu à : *noun*, *verb*, *adjective*, *adverb*, *properNoun*, *other*. Le second fournit un indice du statut du terme : *preferredTerm‐admn‐sts* (recommandé), *admittedTerm‐admn‐sts* (correct), *deprecatedTerm-admn-sts* (déprécié), *supersededTerm‐admn‐sts* (obsolète)|`type`|
|`termSec`|Ensemble des informations pour un terme. Possibilité de lui fournir un identifiant.|`id`|

: {tbl-colwidths="[20,60,20]"}

## Corpus IATE

**IATE :** *InterActive Terminology for Europe*

Base de données terminologique de l’Union Européenne

- format TBX de 2008
- depuis 1999
- normalisation informations
- mise à jour continuellement
- 24 langues UE + latin
- 7,5 M de termes

**Téléchargement :** [https://iate.europa.eu/download-iate](https://iate.europa.eu/download-iate){target="_blank"}

---

### Architecture

- Niveau du concept
  - identifiant
  - domaine
  - commentaire
- Niveau de la langue
  - code langue
- Niveau du terme
  - terme
  - type de terme
  - degré de fiabilité
  - évaluation

---

### Niveau du concept

#### Identifiant

Identifiant unique, préfixé `IATE-`.

```xml
<termEntry id="IATE-14">…</termEntry>
```

#### Domaine

Identifiants numériques reliant l’entrée aux activités de l’Union Européenne, selon le thésaurus [EuroVoc](https://publications.europa.eu/en/web/eu-vocabularies){target="_blank"}.

```xml
<descripGrp>
  <!-- mechanical engineering, electronics and electrical engineering -->
  <descrip type="subjectField">6821, 6826</descrip>
</descripGrp>
```

#### Commentaire

Informations relatives au contexte spécifique d’application du domaine.

```xml
<descripGrp>
  <descrip type="subjectField">6411, 6821</descrip>
  <note>refrigeration</note>
</descripGrp>
```

---

### Niveau de la langue

#### Code langue

Code ISO 639-1 (sur deux lettres) des langues de l’Union Européenne. Un code `mul` pour *multilingue* est étiqueté sur les concepts indépendants de tout langage.

```xml
<!-- Danois -->
<langSet xml:lang="da">…</langSet>
```

### Niveau du terme

#### Terme

Mot ou ensemble de mots qui désignent un concept dans la langue spécifiée au niveau supérieur.

```xml
<tig>
  <term>βήμα χρόνου</term>
</tig>
```

---

#### Type de terme

Choix parmi le vocabulaire suivant : *fullForm*, *abbreviation*, *phraseologicalUnit*, *formula*, *shortForm*.

```xml
<tig>
  <term>E 228</term>
  <termNote type="termType">shortForm</termNote>
</tig>
```

#### Degré de fiabilité

Échelle numérique de 1 à 4 : non vérifié (1), fiabilité minimale (2), fiable (3), autorité (4).

```xml
<tig>
  <term>regenwater</term>
  <descrip type="reliabilityCode">3</descrip>
</tig>
```

#### Évaluation

Statut administratif du terme : obsolète (*supersededTerm-admn-sts*), déprécié (*deprecatedTerm-admn-sts*), correct (*admittedTerm-admn-sts*), à utiliser de préférence (*preferredTerm-admn-sts*).

```xml
<tig>
  <term>sofazne motnje</term>
  <termNote type="administrativeStatus">preferredTerm-admn-sts</termNote>
</tig>
```

---

### Extrait

```xml
<termEntry id="IATE-1436822">
  <descripGrp>
    <descrip type="subjectField">3221</descrip>
  </descripGrp>
  <langSet xml:lang="da">
    <tig>
      <term>dokumentalist</term>
      <termNote type="termType">fullForm</termNote>
      <descrip type="reliabilityCode">3</descrip>
    </tig>
  </langSet>
  <langSet xml:lang="de">
    <tig>
      <term>Dokumentalist</term>
      <termNote type="termType">fullForm</termNote>
      <termNote type="administrativeStatus">deprecatedTerm-admn-sts</termNote>
      <descrip type="reliabilityCode">3</descrip>
    </tig>
    <tig>
      <term>Dokumentar</term>
      <termNote type="termType">fullForm</termNote>
      <termNote type="administrativeStatus">preferredTerm-admn-sts</termNote>
      <descrip type="reliabilityCode">3</descrip>
    </tig>
  </langSet>
</termEntry>
```